language: php

php:
  - 7.3.8

install:
  - composer install
  - composer dump -o

cache:
  directories:
  - vendor

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - composer require php-coveralls/php-coveralls
  - travis_retry php vendor/bin/php-coveralls